<a href="https://colab.research.google.com/github/oarthurcarvalho/100DaysofCode/blob/main/011_020_exercicios_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Conteúdo:
* [Importando a biblioteca](#0)
* [Exercício 11](#1)
* [Exercício 12](#2)
* [Exercício 13](#3)
* [Exercício 14](#4)
* [Exercício 15](#5)
* [Exercício 16](#6)
* [Exercício 17](#7)
* [Exercício 18](#8)
* [Exercício 19](#9)
* [Exercício 20](#10)

### <a name='0'></a> Importando a biblioteca

In [1]:
import numpy as np

np.__version__

'1.21.6'

### <a name='1'></a> Exercício 11
Crie um numpy array 1D com todos os números de 2 dígitos.

__Resultado Esperado:__
```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])
```


In [2]:
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

### <a name='2'></a> Exercício 12

Crie um numpy array específico abaixo:

```
array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
```

Note que o formato do array é (9, 10).

In [3]:
a = np.arange(10,100)

a.reshape((9,10))

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Lembrete

### Matriz Identidade:

Matriz Identidade - uma matriz quadrada cujo os coeficientes são dados pela fórmula:
$${\displaystyle a_{ij}={\begin{cases}1\quad {\text{dla}}\quad i=j\\[2pt]0\quad {\text{dla}}\quad i\neq j\end{cases}}}$$

#### Exemplos:
${\displaystyle I_{1}={\begin{bmatrix}1\end{bmatrix}},\;I_{2}={\begin{bmatrix}1&0\\0&1\end{bmatrix}},\;I_{3}={\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}}}$

### <a name='3'></a> Exercício 13

Crie uma matriz identidade _6x6_. Defina o tipo do dados como _int_.

__Resultado Esperado:__

```
array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])
```


In [4]:
np.eye(6,6, dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### <a name='4'></a> Exercício 14

Defina o seed igual à 10. Então crie um array 1D com 30 valores pseudoaleatórios gerados a partir da distribuição uniforme entre o intervalo $ [0, 1) $.

__Resultado Esperado:__

```
array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895])
```


In [5]:
np.random.seed = 10
np.random.rand(30)

array([0.47145252, 0.66703506, 0.58249886, 0.70363009, 0.24083484,
       0.81506241, 0.9072379 , 0.43866631, 0.91644165, 0.36132934,
       0.71051854, 0.84415867, 0.63846802, 0.67383325, 0.9702306 ,
       0.83950191, 0.7637156 , 0.13480515, 0.43948656, 0.59731915,
       0.90986961, 0.2946562 , 0.50577638, 0.58178567, 0.23471143,
       0.69292848, 0.09999459, 0.37564771, 0.78036737, 0.0709257 ])

### <a name='5'></a> Exercise 15

Defina o seed igual à 20. Então crie um numpy array 1D de formato _(10, 4)_ com valores pseudoaleatórios  gerados por uma distribuição normal padrão de $ N (0, 1) $.

__Resultados Esperados:__
```
array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644],
       [ 0.12877835, -2.06694872, -0.88549315, -1.10457948],
       [ 0.93286635,  2.059838  , -0.93493796, -1.61299022],
       [ 0.52706972, -1.55110074,  0.32961334, -1.13652654]])
```



In [6]:
np.random.seed = 20
np.random.rand(10,4)

array([[0.24977765, 0.51737571, 0.63323911, 0.96163032],
       [0.64606756, 0.28035174, 0.14902551, 0.43090252],
       [0.36524523, 0.30975845, 0.38310086, 0.79640518],
       [0.20422493, 0.85056197, 0.14831232, 0.23238204],
       [0.20959179, 0.859673  , 0.33177133, 0.94778752],
       [0.7506177 , 0.76302113, 0.30845298, 0.55629783],
       [0.17347812, 0.18031866, 0.16598793, 0.05463248],
       [0.93362647, 0.33041131, 0.13195025, 0.90735325],
       [0.15425972, 0.1400543 , 0.94339601, 0.52322552],
       [0.65530639, 0.53046619, 0.54629084, 0.58590227]])

### <a name='6'></a> Exercício 16
Defina o seed igual à 30. Então crie um numpy array 2D com o formato _(10, 4)_ com valores pseudoaleatórios gerados por uma distribuição normal padrão de $ N (100, 5) $.
$\mu=100$   
$\sigma^{2}=5$


__Resultado Esperado:__
```
array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365],
       [ 99.98708001,  98.95468525,  99.05410904, 102.38025432],
       [ 93.50787269, 103.61547679, 103.18753701,  98.51356237],
       [102.20256689,  96.19764407,  97.54000366,  97.05813038],
       [101.81233513,  97.66380453,  98.45883627,  98.09317768],
       [102.48979932,  95.70413391,  98.43161651, 101.89861815]])
```



In [8]:
np.random.seed = 20

sigma = np.sqrt(5)
mu = 100

sigma * np.random.randn(10, 4) + mu

array([[ 98.59362668, 103.51401885, 102.50032871,  98.73653246],
       [100.82685264,  97.07710569, 102.51336945,  99.34074024],
       [102.74091253,  98.64650265,  99.63447218,  97.06200785],
       [ 99.88775444,  99.52882393, 104.17312818,  99.89420338],
       [ 97.21994619, 101.51135277,  99.40896051, 100.64435252],
       [103.50718949,  99.02553061,  98.17260953,  99.53017098],
       [102.85648908, 101.7548658 ,  98.14132495, 100.77842367],
       [ 99.11292593, 102.78323997, 101.58362896,  99.19014266],
       [101.44836078,  98.01787224,  98.19673113, 102.23577315],
       [101.76297865,  99.90723223, 100.18080256,  99.95933163]])

### <a name='7'></a> Exercício 17
Iteragindo com array numpy $ A $ elemento por elemento. Escreva cada elemento do array no console.

```
A = np.array([[1, 4, 3],
              [5, 2, 6]])
```

In [14]:
!pip install ipython-autotime -q
%load_ext autotime

The autotime extension is already loaded. To reload it, use:
  %reload_ext autotime
time: 4.85 s (started: 2022-05-20 09:30:36 +00:00)


In [15]:
A = np.array([[1, 4, 3],
              [5, 2, 6]])

for i in np.nditer(A):
    print(i)

1
4
3
5
2
6
time: 2.5 ms (started: 2022-05-20 09:30:54 +00:00)


In [16]:
for i in A:
    for j in i:
        print(j)

1
4
3
5
2
6
time: 2.16 ms (started: 2022-05-20 09:31:02 +00:00)


### <a name='8'></a> Exercício 18
Criar um numpy array 1D (vetor) que  consiste em 11 pontos igualmente espaçados a partir do intervalo $ [0, 1]. $

__Resultado Esperado:__
```
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```

In [18]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

time: 4.49 ms (started: 2022-05-20 09:33:36 +00:00)


### <a name='9'></a> Exercício 19

Defina o seed igual à 42. Gere um array numpy 1D contendo o resultado de um possível jogo da Mega Sena.

__Resultado Esperado:__
```
array([39, 29, 15, 43,  8, 21])
```


In [19]:
np.random.randint(low=1, high=50, size=6)

array([13, 13, 20, 35, 49, 32])

time: 5.38 ms (started: 2022-05-20 09:36:34 +00:00)


### <a name='10'></a> Exercício 20
Crie um array 2D de formato _6x6_ igual o abaixo:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])
```

In [23]:
np.diag(np.arange(6))

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

time: 4.5 ms (started: 2022-05-20 09:39:07 +00:00)
