<a href="https://colab.research.google.com/github/oarthurcarvalho/100DaysofCode/blob/main/011_020_exercicios_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Conteúdo:
* [Importando a biblioteca](#0)
* [Exercício 11](#1)
* [Exercício 12](#2)
* [Exercício 13](#3)
* [Exercício 14](#4)
* [Exercício 15](#5)
* [Exercício 16](#6)
* [Exercício 17](#7)
* [Exercício 18](#8)
* [Exercício 19](#9)
* [Exercício 20](#10)

### <a name='0'></a> Importando a biblioteca

In [1]:
import numpy as np

np.__version__

'1.21.6'

### <a name='1'></a> Exercício 11
Crie um numpy array 1D com todos os números de 2 dígitos.

__Resultado Esperado:__
```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])
```


In [3]:
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

### <a name='2'></a> Exercício 12

Crie um numpy array específico abaixo:

```
array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
```

Note que o formato do array é (9, 10).

In [7]:
a = np.arange(10,100)

a.reshape((9,10))

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Lembrete

### Matriz Identidade:

Matriz Identidade - uma matriz quadrada cujo os coeficientes são dados pela fórmula:
$${\displaystyle a_{ij}={\begin{cases}1\quad {\text{dla}}\quad i=j\\[2pt]0\quad {\text{dla}}\quad i\neq j\end{cases}}}$$

#### Exemplos:
${\displaystyle I_{1}={\begin{bmatrix}1\end{bmatrix}},\;I_{2}={\begin{bmatrix}1&0\\0&1\end{bmatrix}},\;I_{3}={\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}}}$

### <a name='3'></a> Exercício 13

Crie uma matriz identidade _6x6_. Defina o tipo do dados como _int_.

__Resultado Esperado:__

```
array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])
```


In [9]:
np.eye(6,6, dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### <a name='4'></a> Exercício 14

Defina o seed igual à 10. Então crie um array 1D com 30 valores pseudoaleatórios gerados a partir da distribuição uniforme entre o intervalo $ [0, 1) $.

__Resultado Esperado:__

```
array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895])
```


In [25]:
np.random.seed = 10
np.random.rand(30)

array([0.66224645, 0.19207609, 0.35114706, 0.09584568, 0.85927159,
       0.34726151, 0.98007918, 0.41185289, 0.32972057, 0.37094425,
       0.84949219, 0.17002627, 0.74318736, 0.96775226, 0.53397517,
       0.73598276, 0.56515584, 0.95102612, 0.84639252, 0.34218793,
       0.45641586, 0.54025395, 0.22001751, 0.93218018, 0.75414064,
       0.96616726, 0.02973406, 0.11505267, 0.09764775, 0.68825365])

### <a name='5'></a> Exercise 15

Defina o seed igual à 20. Então crie um numpy array 1D de formato _(10, 4)_ com valores pseudoaleatórios  gerados por uma distribuição normal padrão de $ N (0, 1) $.

Então crie um array 1D com 30 valores pseudoaleatórios gerados a partir da distribuição uniforme entre o intervalo $ [0, 1) $.

__Resultados Esperados:__
```
array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644],
       [ 0.12877835, -2.06694872, -0.88549315, -1.10457948],
       [ 0.93286635,  2.059838  , -0.93493796, -1.61299022],
       [ 0.52706972, -1.55110074,  0.32961334, -1.13652654]])
```



In [26]:
np.random.seed = 20
np.random.rand(10,4)

array([[0.21830382, 0.13151726, 0.39503123, 0.57505407],
       [0.48092031, 0.20868083, 0.3614238 , 0.65351422],
       [0.18084943, 0.16148637, 0.74124983, 0.42533956],
       [0.92346756, 0.27807158, 0.04037031, 0.7500117 ],
       [0.76643477, 0.24918193, 0.13414638, 0.21726127],
       [0.68465524, 0.35386819, 0.76235756, 0.73420049],
       [0.98972122, 0.18399377, 0.52219218, 0.67946499],
       [0.34145516, 0.18973883, 0.97067427, 0.19419539],
       [0.80795973, 0.5824129 , 0.87264745, 0.34866459],
       [0.12905768, 0.16107793, 0.23299445, 0.74203681]])

### <a name='6'></a> Exercise 16
Set the random seed to 30. Then build a two-dimensional array with the shape _(10, 4)_ pseudo-random values generated from the normal distribution $ N (100, 5) $.
$\mu=100$   
$\sigma^{2}=5$

__Expected result:__
```
array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365],
       [ 99.98708001,  98.95468525,  99.05410904, 102.38025432],
       [ 93.50787269, 103.61547679, 103.18753701,  98.51356237],
       [102.20256689,  96.19764407,  97.54000366,  97.05813038],
       [101.81233513,  97.66380453,  98.45883627,  98.09317768],
       [102.48979932,  95.70413391,  98.43161651, 101.89861815]])
```
__Tip:__ Use the function _np.random.rand()_.


In [ ]:
# enter solution here

### <a name='7'></a> Exercise 17
Iterating by array numpy $ A $ element by element (element-wise) print each element of the array to the console.

```
A = np.array([[1, 4, 3],
              [5, 2, 6]])
```

__Tip:__ Use the _np.nditer()_ function.


In [ ]:
# enter solution here

### <a name='8'></a> Exercise 18
Create a one-dimensional numpy array (vector) consisting of 11 equally spaced points from the interval $ [0, 1]. $

__Expected result:__
```
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```
__Tip:__ Use the _np.linspace()_ function.



In [ ]:
# enter solution here

### <a name='9'></a> Exercise 19

Set the random seed to 42. Generate a one-dimensional array (vector) containing the possible result from the Big Lotto game.

__Expected result:__
```
array([39, 29, 15, 43,  8, 21])
```

__Tip:__ The result of the game is a 6-element vector of values from 1 to 49 inclusive.



In [ ]:
# enter solution here

### <a name='10'></a> Exercise 20
Build the two-dimensional _6x6_ size array below:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])
```
__Tip:__ Use the _np.diag()_ function.



In [ ]:
# enter solution here