<a href="https://colab.research.google.com/github/oarthurcarvalho/100DaysofCode/blob/main/001_010_exercicios_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Table of contents:
* [Importando a Biblioteca](#0)
* [Exercício 1](#1)
* [Exercício 2](#2)
* [Exercício 3](#3)
* [Exercício 4](#4)
* [Exercício 5](#5)
* [Exercício 6](#6)
* [Exercício 7](#7)
* [Exercício 8](#8)
* [Exercício 9](#9)
* [Exercício 10](#10)

### <a name='0'></a> Importando a Biblioteca

In [1]:
import numpy as np

np.__version__

'1.21.6'

### <a name='1'></a> Exercício 1
Verifique se todos os elementos dos arrays $ A, B, C $ e $ D $ retornam o valor lógicos _True_.

```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])
```

In [10]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.all(array)}')

A: True
B: False
C: False
D: True


### <a name='2'></a> Exercício 2
Verifique se todos os elementos dos arrays $ A, B $ e $ C $ retornam o valor lógicos _True_ ao longo do eixo com index 1.


```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
```

In [12]:
# enter solution here
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

for name, array in zip(list('ABC'), [A, B, C]):
    print(f'{name}: {np.all(array, axis=1,)}')

A: [ True  True]
B: [ True False]
C: [False  True]


### <a name='3'></a> Exercício 3
Verifique se alguns elementos dos arrays $ A, B, C $ e $ D $ retornam o valor lógicos _True_.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```

In [13]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list('ABCD'), [A,B,C,D]):
    print(f'{name}: {np.any(array)}')

A: False
B: True
C: True
D: True


### <a name='4'></a> Exercício 4
Verifique se alguns elementos dos arrays  $ A, B, C $ e $ D $ retornam o valor lógicos _True_ ao longo do eixo com index 0.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```



In [14]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list('ABCD'), [A,B,C,D]):
    print(f'{name}: {np.any(array, axis=0)}')

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


### <a name='5'></a> Exercício 5
Verifique se o array $ A $ tem dado faltante (_np.nan_).

```
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
```


In [16]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


### <a name='6'></a> Exercício 6
Verifique se os arrays $ A $ e $ B $ abaixo são iguais em termos de elementos (element-wise) com uma tolerância específica. 

```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
```

In [17]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

'''
rtol: float -> Tolerância Relativa = 1e-05

atol: float -> Tolerância Absoluta = 1e-08
'''
np.allclose(A, B)

True


### <a name='7'></a> Exercicio 7
Verifique se os seguintes arrays $ A $ e $ B $ são iguais em termos de elementos usando o operador _==_.

```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
```

In [19]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

print(A == B)

[False False  True]


### <a name='8'></a> Exercício 8

Verificar quais elementos (element-wise) do array $ A $ abaixo tem valores mais altos que o array $ B $.

```
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
```

In [22]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

print(A > B)

[ True False False False]


### <a name='9'></a> Exercício 9

Crie um array do numpy com dimensões _4x4_, todos com valores iguais a 0. Defina os tipos de dados para _int_.

__Resultado Esperado:__

```
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
```

In [28]:
A = np.zeros((4,4), dtype=int)
A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### <a name='10'></a> Exercício 10
Crie uma matriz com dimensões _10x10_ preenchida com o número 255. Defina o tipo do dado como _float_.

__Resultado Esperado:__
```
array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])
```

In [29]:
A = np.ones((10,10), dtype=float) * 255

A

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])